version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./mongo:/data/db
      - ./mongo/dump:/dump
    ports:
      - "27017:27017"
    networks:
      - practica_net

  backend_container:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    container_name: backend_container
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017
      - MONGO_URL=mongodb://mongodb:27017/libros
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    networks:
      - practica_net
    command: npm start

  frontend_container:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    container_name: frontend_container
    depends_on:
      - backend_container
    ports:
      - "4200:4200"
    networks:
      - practica_net
  
  adminMongo_container:
    image: mongo-express:latest
    container_name: adminMongo_container
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    networks:
      - practica_net
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_BASICAUTH_USERNAME: ''
      ME_CONFIG_BASICAUTH_PASSWORD: ''

  nginx_container:
    image: nginx:latest
    container_name: nginx_container
    volumes:
      - ./loadbalancer/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on: 
      - frontend_container
    networks:
      - practica_net
     
  prometheus_container:
    image: prom/prometheus:v2.20.1
    container_name: prometheus_practica
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - practica_net

  grafana_container:
    image: grafana/grafana:7.1.5
    container_name: grafana_practica
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel@1.0.1
      - GF_INSTALL_PLUGINS=grafana-clock-panel, grafana-simple-json-datasource, natel-discrete-panel, grafana-piechart-panel
    volumes:
      - myGrafanaVol:/var/lib/grafana
      - /usr/src/app/datasources.yml
    ports:
      - "3500:3000"
    depends_on:
      - prometheus_container
    networks:
      - practica_net

networks:
  practica_net:
    driver: bridge

volumes:
  mongo:
  myGrafanaVol:

